config/routes.rb
Campernotities::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  match "/campings/:id" => "campings#show", :as => :camping
  match "/authors/:id" => "authors#show", :as => :author
  match "/authors" => "authors#index", :as => :authors

  get "maps" => "maps#index"

  root :to => "authors#home"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  validates_presence_of :name

  has_many :campings, :foreign_key => :author_id
end

app/models/camping.rb
class Camping < ActiveRecord::Base
  attr_accessible :description, :name, :images_attributes, :labels_attributes, :latitude, :longitude, :website

  after_find :set_fallback_images

  belongs_to :author, :class_name => AdminUser
  validates_presence_of :author

  has_many :labels
  accepts_nested_attributes_for :labels

  has_many :images
  accepts_nested_attributes_for :images, :allow_destroy => true

  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude

  validate :lat_lon_combination
  validates :latitude, :numericality  => { :greater_than_or_equal_to => -90, :less_than_or_equal_to  => 90 }, :allow_blank  => true
  validates :longitude, :numericality => { :greater_than_or_equal_to => -180, :less_than_or_equal_to => 180 }, :allow_blank => true

  validates :website,
    :length => { :maximum => 255 },
    :format => { :with => URI::regexp(%w(http https)) },
    :allow_nil => true
  before_validation :ensure_website_has_protocol

  default_scope order("created_at")
  # Scope for anything with geocodes. Check for latitude-only, since we never have a record with only longitude.
  scope :geocoded, where("latitude <> 'NULL'")

  # Scope for "top" campings
  def self.top(amount)
    order(:created_at).limit(amount)
  end

  # Utility for fetching the main image
  def main_image
    images.first.image
  end

  # Validation callbacks
  def lat_lon_combination
    if (latitude.blank? ^ longitude.blank?)
      errors.add(:base, "When providing a location, both Latitude and Longitude should be provided")
    end
  end
  def ensure_website_has_protocol
    unless website.nil?
      self.website = "http://#{website}" if URI.parse(website).scheme.nil?
    end
  end

  private
  def set_fallback_images
    self.images << Image.new if images.count == 0
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :alt, :image

  # Paperclip
  has_attached_file :image,
    :default_url => "/assets/missing.jpg",
    :styles => { 
      :thumb => "150x150>",
      :large => "1000x"
    }
  validates :image, 
    :presence => :true,
    :attachment_content_type => { :content_type => ["image/jpg", "image/jpeg", "image/png"] },
    :attachment_size => { :in => 0..5.megabytes }
end

app/models/label.rb
class Label < ActiveRecord::Base
  attr_accessible :name, :value

  belongs_to :camping

  validates_presence_of :name
  validates_length_of :name, :within => 2..60

  scope :selects, where("value <> ?", "")
  scope :flags,   where("value = ?",  "")

  def self.top amount
    find(:all, :select => '*, count(*) AS count', :group => 'name', :order => 'count DESC', :limit => amount)
  end

  def options
    self.class.select(:value).where(:name => name).order("value ASC").uniq.map {|t| t.value }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = AdminUser.find(:all)
    @title   = "Discover Campings by Author"
  end

  def home
    @authors = AdminUser.find(:all)
    @campings = Camping.top(10)
  end

  def show
    @author   = AdminUser.find(params[:id])
    @campings = @author.campings
    @title    = "Discover Campings by #{@author.name}"
  end
end

app/controllers/campings_controller.rb
class CampingsController < ApplicationController
  def show
    @camping = Camping.find(params[:id])
    @title   = @camping.name
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
    @title = "Discover Campings by Location"
    @center = center_params
    @search = Camping.search(params[:search])
    @flags   = Label.flags.top(10)
    @selects = Label.selects.top(10)
    @campings = []

    unless params[:bounding].nil?
      box = params[:bounding].split(',').map{|bearing| bearing.to_f}
      Camping.within_bounding_box(box).top(50).search(params[:search]).each do |camping|
        rendered = camping.attributes
        rendered["listing"] = render_to_string(
          :file => "campings/_camping",
          :formats =>   "html",
          :layout  => false,
          :locals => {:camping => camping})
        rendered["infowindow"] = render_to_string(
          :file => "campings/_infowindow",
          :formats => "html",
          :layout => false,
          :locals => {:camping => camping})

        @campings << rendered
      end
    end

    respond_to do |format|
      format.html
      format.json { render :json => @campings }
    end
  end

  private
  def center_params
    lat, lon = params[:center].try(:split, ',')
    { :lat => (lat || '51.71154'), lon: (lon || '6.0503') }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    @title || "Share and Discover those Special Campings"
  end

  def m(text)
    RDiscount.new(text.to_s, :filter_html).to_html
  end
end

app/helpers/campings_helper.rb
module CampingsHelper
  def map_tag(lat, lon)
    location = "#{lat},#{lon}"
    link_to({:controller => :maps, :action => :index, :center => location}, {:class => :map}) do
      image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{location}&size=458x300&zoom=11&sensor=false&markers=#{location}&maptype=hybrid", :class => "map", :alt => "map"
    end
  end
end

app/views/authors/home.haml
#authors
  #stretcher
  .row
    #fp-selector.four.columns.centered
      .large.button.dropdown{:href => "#"}
        Show me campings by
        %ul
          - @authors.each do |author|
            %li
              %a{:href => author_path(author)}
                =author.name
  #content.row
    = render :partial => "campings/camping", :collection => @campings

app/views/authors/index.haml
#content.row
  %h1.title
    = title
  - @authors.each do |author|
    %section
      %h2
        %a{:href => author_path(author)}
          = author.name
      %ul.block-grid.four-up.mobile
        - author.campings.top(5).each do |camping|
          %li
            %a.th{:href => camping_path(camping)}
              = image_tag camping.main_image.url

app/views/authors/show.haml
.row
  %h1.title
    Discover Campings by
    = @author.name
  = render :partial => "campings/camping", :collection => @campings

app/views/campings/_camping.haml
%article
  %h1
    = link_to camping.name, camping_path(camping)
  %ul.block-grid.four-up.mobile
    - camping.images.limit(4).each do |image|
      %li
        %a.th{:href => camping_path(camping)}
          = image_tag image.image.url(:thumb)
  .more
    = link_to "read more", camping_path(camping)

app/views/campings/_infowindow.haml
%h2.small
  = link_to camping.name, camping
.row
  .four.columns
    %a.th{:href => camping_path(camping)}
      = image_tag camping.main_image.url(:thumb)
  .eight.columns
    = camping.description
.more
  = link_to "read more", camping

app/views/campings/show.haml
.row
  %article
    %h1
      = @camping.name
    #featured.twelve.colums
      - @camping.images.each do |image|
        = image_tag image.image.url(:large), :class => "large", :data => { :thumb => image.image.url(:thumb) }
    .row
      .six.columns.description
        != m @camping.description
      .six.columns
        = map_tag(@camping.latitude, @camping.longitude) unless @camping.latitude.blank?
        %table.twelve.properties
          %tbody
            - unless @camping.latitude.blank?
              %tr.geo
                %td.name
                  Geo
                %td.value
                  = "#{@camping.latitude}, #{@camping.longitude}"
            - unless @camping.website.blank?
              %tr.website
                %td.name
                  Website
                %td.value
                  = link_to "#{@camping.name} website", @camping.website

            - @camping.labels.each do |label|
              %tr.filter-label
                %td.name
                  = label.name
                %td.value
                  = label.value

- content_for :javascript_body do
  = render(:partial => "shared/orbit", :formats => [:js])

app/views/images/_thumb.haml
= image_tag(thumb.image.url(:thumb))

app/views/labels/_label.html.haml
%dl
  %dt
    = label.name
  %dd
    = label.value

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	
	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
	
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
	<title><%= title %> - ShareShire</title>

	<!-- Included CSS Files -->
	<%= stylesheet_link_tag    "application" %>
	
	<!-- Included JS Files  -->
	<%= javascript_include_tag "application" %>
  <%= yield :javascript_tags %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "shared/top_bar" %>
  <%= yield %>

  <%- if content_for?(:javascript_body) %>
    <script>
      <%= yield(:javascript_body) %>
    </script>
  <% end %>
</body>
</html>

app/views/maps/index.html.haml
- content_for :javascript_tags do
  = javascript_include_tag "http://maps.googleapis.com/maps/api/js?key=AIzaSyC1GdwD4o0-PSz_5afcPM5_P_OsKZGf6Fg&sensor=true"

- content_for :javascript_body do
  $(document).ready(function() {                        |
    map.setup('#{@center[:lat]}', '#{@center[:lon]}');  |
  });                                                   |

.row
  %h1.title
    = title
  = form_for(@search, :url => maps_path(:format => :json), :html => { :method => :get }) do |f|
    .row.collapse
      .ten.columns
        = text_field_tag("search_contains", nil, :placeholder => "Enter search terms...", :name => "search[name_or_description_contains]")
      .two.columns
        = f.submit "Search", :class => "button expand postfix"
    .row
      .twelve.columns.filters
        %fieldset.collapsible.collapsed
          %legend Refine
          .six.columns.flags
            .row
              - @flags.each do |label|
                .six.columns
                  = label_tag("label_#{label.id}", label.name, :class => "right inline" )
                .six.columns
                  = check_box_tag("label_#{label.id}", label.name, [f.object.labels_name_eq_any].flatten.include?(label.name), :name => "search[labels_name_eq_any][]")
          .six.columns.selects
            .row
              - @selects.each do |select|
                .six.columns
                  = label_tag("label_#{select.id}", select.name, :class => "right inline")
                .six.columns
                  = select_tag("label_#{select.id}", options_for_select(select.options, [f.object.labels_value_eq_any].flatten.first), :include_blank => true, :name => "search[labels_value_eq_any][]")
  #map_canvas.twelve.columns

#campings.row
  Please wait ....

app/views/shared/_orbit.js.erb
$(window).load(function(){
  $("#featured").orbit({
    animation: "fade",
    timer: false,
    captions: false,
    bullets: true,
    bulletThumbs: true
  });
});

app/views/shared/_top_bar.haml
%nav.top-bar
  %ul
    %li
      %a.name{:href => root_path, :title => "To homepage"}
        = image_tag "logo.png", :alt => "ShareShire"
    %li.toggle-topbar
      %a{:href => "#"}
  %section
    %ul.left
      %li.divider
      %li
        %a{:href => authors_path} Authors
      %li.divider
      %li
        %a{:href => maps_path} Locations
      %li.divider
    %ul.right
      %li.divider
      - if admin_user_signed_in?
        %li
          %a
            Hi there,
            = current_admin_user.name
        %li.divider
      %li
        - if admin_user_signed_in?
          %a{:href => admin_dashboard_path, :title => "Visit administration"}
            Administration
        - else
          %a{:href => new_admin_user_session_path, :title => "Login for writers"}
            Login